# Changes here will be overwritten by Copier
_commit: 8048e81
_src_path: gh:acid9reen/python_template
author: Ruslan Smirnov
package_name: egm_dataset_generator
project_name: EGM dataset generator
project_short_description: Set of tools to generate dataset from egm signals and labels
    of heartbeats
python_version: '3.10'
